# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TepJdo7xQW6og0-dT16lifx9ex4IbKju
"""

print("sssssssssss")

print("bybye")